# Generated by Django 3.2.5 on 2021-09-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add',
            new_name='student',
        ),
    ]
